[package]
name = "lex-service"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
fastrace.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
