[package]
name = "lex-http"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
fastrace.workspace = true
tokio = { workspace = true, features = ["net"] }
